/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mandelbrotset;

import java.awt.Graphics;
import java.util.Stack;

/**
 *
 * @author trinch
 */
public class FractalPlant extends javax.swing.JPanel {
    
    String seq = "X"; // axiom
    Stack stack;
    int scale = 6;
    /**
     * Creates new form FractalPlant
     */
    public FractalPlant() {
        initComponents();
        buildString(6);
        stack = new Stack();
        
    }
   

    
    @Override
    public void paintComponent(Graphics g)
    {
        System.out.println("painting");
        super.paintComponent(g); // Do the original draw
        scale = (int) Math.round( (this.getHeight() / 150.0) );
        drawString(g, this.getHeight(), this.getWidth());
    }
    
    public void drawString(Graphics g, int height, int width) {
        /*0: draw a line segment ending in a leaf
        1: draw a line segment
        [: push position and angle, turn left 45 degrees
        ]: pop position and angle, turn right 45 degrees*/
        
        
        /* 
           F means "draw forward"
           − means "turn left 25°"
           + means "turn right 25°"
           X does not correspond to any drawing action
           [ corresponds to saving the current values for position and angle
           [ corresponds to restoring the current values for position and angle
        */
        int angle = 0;
        int x = 3*width/7, y = height; // start drawing at bottom middle pixel of the screen
        int newx = 0, newy = 0;
        
        for(int i=0; i<seq.length(); i++) {
            if (seq.charAt(i) == 'F') {
                
                newx = x + (int)(scale * Math.sin(((2*Math.PI)/360) * angle));// (int)(scale/2 * Math.sqrt(2));
                newy = y - (int)(scale * Math.cos(((2*Math.PI)/360) * angle));
                
                g.drawLine(x, y, newx, newy);
                
            } else if(seq.charAt(i) == '+') {
                
                angle += 25; 
                if (angle > 180)
                    angle = - (360 - angle);
                
            } else if(seq.charAt(i) == '-') {
                System.out.println("-25");
                angle -= 25; 
                if (angle <= -180)
                    angle = (360 + angle);
                
            } else if(seq.charAt(i) == ']') {
                
                // ]: pop position and angle
                angle = (int) this.stack.pop();
                newy = (int) this.stack.pop();
                newx = (int) this.stack.pop();

            } else if(seq.charAt(i) == '[') {
                
                // [: push position and angle
                this.stack.push(x);
                this.stack.push(y);
                this.stack.push(angle);
            }
            
            x = newx;
            y = newy;
        }
    }
    
    public void rewrite() {
        String newSeq = new String();
        
        // for every character execute a rewrite rule
        for(int i=0; i<seq.length(); i++) {
            if (seq.charAt(i) == 'X') {
                newSeq = newSeq.concat("F-[[X]+X]+F[+FX]-X");
            } else if(seq.charAt(i) == 'F') {
                newSeq = newSeq.concat("FF");
            } else {
                newSeq = newSeq.concat(Character.toString(seq.charAt(i)));
            }
        }
        
        this.seq = newSeq;
    }
    
    public void buildString(int n) {
        for(int i=0; i<n; i++) {
            rewrite();
            System.out.println(this.seq);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
